### GET REQUEST
GET http://localhost:3000/api/games/1234


### POST REQUEST
POST http://localhost:8000
content-type: application/json


{"test":"1232324",
    "status":"updated"
}


### PUT REQUEST
PUT http://localhost:3000/api/games/1234
content-type: application/json


{
    "bingoNumber":13
}

### DELETE REQUEST
DELETE http://localhost:8000/assignmentSixds/apiRequests/644584527726e807c87376bd