POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "pragdssdygdn@gmail.com",
    "password":"pragyan123",
    "firstname" :"Pragyan",
    "lastname" : "B",
    "age":22,
    "phone": 8597864583

 }